# 服务器配置
server:
  port: 8080
  mode: "debug"

# Redis 配置
redis:
  host: "localhost"
  port: 6379
  password: "123456"
  db: 0

# MongoDB 配置
mongodb:
  url: "mongodb://admin:123456@localhost:27017/"
  dbname: "test"